application: step15-krispop
version: 1
runtime: go
api_version: go1

handlers:
- url: /favicon.ico
  static_files: ico/wind.gif
  mime_type: image/gif
  upload: ico/wind.gif

- url: /pure
  static_dir: pure
  mime_type: text/css

- url: /.*
  script: _go_app
