application: step-test-krispop
version: 1
runtime: go
api_version: go1

handlers:
- url: /scripts
  static_dir: scripts

- url: /upgit
  static_files: scripts/upgit
  upload: scripts/upgit

- url: /favicon.ico
  static_files: ico/favicon.gif
  mime_type: image/gif
  upload: ico/favicon.gif

- url: /.*
  script: _go_app

